# Generated by Django 5.2.6 on 2025-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
